name: Create New Game
run-name: ${{github.actor}} is creating a new game
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  create-game:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{secrets.USER_NAME}}
      PASSWORD: ${{secrets.PASSWORD}}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run createGame
      - run: echo "New game has been created 🚀"
